apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-ui
  namespace: workspace-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-ui
  template:
    metadata:
      labels:
        app: workspace-ui
    spec:
      containers:
      - name: nginx
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/workspace-ui:${DEPLOYMENT_TAG}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-ui
  namespace: workspace-system
spec:
  selector:
    app: workspace-ui
  ports:
  - port: 80
    targetPort: 80