apiVersion: v1
kind: Secret
metadata:
  name: workspace-auth-secret
  namespace: workspace-system
type: Opaque
data:
  # Generate with: echo -n "your-jwt-secret-key" | base64
  jwt-secret: "${JWT_SECRET}"
